'use strict';

const types = `
    type Author {
        id: ID!
        name: String
    }
    extend type Query {
        author(id: ID!) : Author
    }
`;

//TODO: Query and Mutations will be auto generated by parsing the types AST
const resolvers = {
    Query: {
        author(_, { id }, { act }) {
            return act({ query: 'author' }, { id });
        }
    }
};

module.exports = { types, resolvers };
