'use strict';

const types = `
    type Book {
        id: ID!
        name: String
    }
    extend type Query {
        book(id: ID!) : Book
    }
`;

//TODO: Query and Mutations will be auto generated by parsing the AST of the types
const resolvers = {
    Query: {
        book: async function (_, { id }, context) {
            try {
                return await context.act({ query: 'book' }, { id });
            }
            catch (error) {
                if (error.code === 'act_not_found') {
                    error.statusCode = 404;
                }
                else {
                    error.statusCode = 500;
                }
                throw error;
            }
        }
    }
};

module.exports = { types, resolvers };
